# Generated by Django 4.1.7 on 2023-04-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Question')),
                ('question_text', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Published at')),
                ('answers', models.ManyToManyField(to='Polls.answers', verbose_name='Answers')),
            ],
        ),
    ]
